FROM python:3.12-slim AS backend-runtime

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

RUN rm -f /app/types.py

RUN chmod +x backend-start.sh

EXPOSE 80

CMD ["./backend-start.sh"]
