FROM python:3.12-slim AS backend-runtime

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

# remove python internal module conflict
RUN rm -f /app/types.py

# verify python environment
RUN python - <<'PY'
import sys
import types
print("Python OK")
print(types.__file__)
PY

RUN chmod +x backend-start.sh

EXPOSE 80

CMD ["./backend-start.sh"]
