name: Build and Push Afran Images

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: registry-dba221617d-afran-allocation.apps.ir-central1.arvancaas.ir
  API_IMAGE: registry-dba221617d-afran-allocation.apps.ir-central1.arvancaas.ir/afran-allocation-api:1.1.0
  FRONTEND_IMAGE: registry-dba221617d-afran-allocation.apps.ir-central1.arvancaas.ir/afran-allocation-frontend:0.1.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login Arvan Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Backend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: ${{ env.API_IMAGE }}

      - name: Build Frontend Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}
