name: Build and Push Afran Frontend

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and push Frontend 0.1.0
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Login to Arvan Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: Build and push Frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./Dockerfile.frontend
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/afran-allocation-frontend:0.1.0
